// Generated by CoffeeScript 1.4.0
(function() {
  var app, connect;

  connect = require('connect');

  app = connect();

  app.use(connect["static"]('static'));

  app.listen(9999);

}).call(this);
